import { createDataService } from "./data-service.js";
import { computeLeaderboard, rankLeaderboard, totalClassXp, getActiveSeason, getSeasonGoal, completedBooksCount, userRecords } from "./stats.js?v=20260915-seasons1";
const $ = (id) => document.getElementById(id);
const esc = (v="") => String(v).replace(/[&<>'"]/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function renderPodium(rows){const medals=["🥈","🥇","🥉"],order=[rows[1],rows[0],rows[2]];$("podium").innerHTML=order.map((r,i)=>r?`<div class="podium-card ${i===1?"first":""}"><div class="podium-place">${medals[i]}</div><b>${esc(r.nickname)}</b><span>${r.xp} XP</span></div>`:"<div></div>").join("");}
function weekStart(date){const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()-((d.getDay()+6)%7));return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function longest(state,uid){const dates=[...new Set(userRecords(state,uid).filter(r=>Number(r.xp)>0).map(r=>r.date))].sort();let best=0,run=0,last=null;dates.forEach(date=>{const n=Math.floor(new Date(`${date}T12:00:00`).getTime()/86400000);run=last!==null&&n===last+1?run+1:1;best=Math.max(best,run);last=n;});return best;}
function records(state,rows){const weeks=new Map();rows.forEach(r=>userRecords(state,r.uid).forEach(x=>{const w=weekStart(x.date);weeks.set(w,(weeks.get(w)||0)+Number(x.xp||0));}));const best=[...weeks.entries()].sort((a,b)=>b[1]-a[1])[0]||null,books=rows.map(r=>({...r,value:completedBooksCount(state,r.uid)})),streaks=rows.map(r=>({...r,value:longest(state,r.uid)})),mb=Math.max(0,...books.map(r=>r.value)),ms=Math.max(0,...streaks.map(r=>r.value));return {week:best?best[1]:0,books:mb,bookNames:mb?books.filter(r=>r.value===mb).map(r=>r.nickname):[],streak:ms,streakNames:ms?streaks.filter(r=>r.value===ms).map(r=>r.nickname):[]};}
function ensureRecords(){if($("presentationRecords"))return;const card=document.createElement("section");card.id="presentationRecords";card.className="card";card.style.marginTop="18px";card.innerHTML='<div class="section-head"><div><h3>Klassenrekorde</h3><p>Aktuelle Season</p></div></div><div id="presentationRecordMetrics" class="metrics"></div>';$("leaderboard").closest("section")?.insertAdjacentElement("afterend",card);}
const service=await createDataService();await service.initStudentSession();$("modeBadge").textContent=service.mode==="demo"?"● DEMO":"● LIVE";$("modeBadge").className=`badge ${service.mode==="demo"?"demo":"live"}`;
service.subscribeState(state=>{const season=getActiveSeason(state),rows=rankLeaderboard(computeLeaderboard(state)),total=totalClassXp(state),goal=getSeasonGoal(state),percent=Math.min(100,Math.round(total/Math.max(1,goal)*100));$("title").textContent=state.config.className||"LESELIGA 11";$("season").textContent=season.label;$("totalXp").textContent=total;$("goalXp").textContent=goal;$("goalBar").style.width=`${percent}%`;$("goalText").textContent=total>=goal?"🎉 Season-Klassenziel erreicht – jetzt geht es um Bonus-XP!":`Noch ${goal-total} XP bis zum Season-Klassenziel.`;$("count").textContent=`${rows.length} Teilnehmer · Top 10`;$("updated").textContent=`Live · ${new Intl.DateTimeFormat("de-DE",{hour:"2-digit",minute:"2-digit"}).format(new Date())}`;renderPodium(rows);$("leaderboard").innerHTML=rows.slice(0,10).map(r=>`<div class="rank-row"><div class="rank">${r.rank}</div><div class="player"><b>${esc(r.nickname)}</b></div><div class="score">${r.xp} XP</div></div>`).join("")||'<div class="empty">Noch keine Teilnehmer.</div>';ensureRecords();const rec=records(state,rows);$("presentationRecordMetrics").innerHTML=`<div class="metric"><b>${rec.week} XP</b><span>beste Klassenwoche</span></div><div class="metric"><b>${rec.books}</b><span>meiste Bücher${rec.bookNames.length?` · ${esc(rec.bookNames.join(", "))}`:""}</span></div><div class="metric"><b>${rec.streak}</b><span>längste Streak${rec.streakNames.length?` · ${esc(rec.streakNames.join(", "))}`:""}</span></div>`;});
