import { createDataService } from "./student-data-service.js?v=20260916-privacy1";
import { computeLeaderboard, rankLeaderboard, totalClassXp, getActiveSeason, getSeasonGoal, getPublicSeasonStats } from "./stats.js?v=20260916-privacy1";
const $=id=>document.getElementById(id);
const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function renderPodium(rows){const medals=["🥈","🥇","🥉"],order=[rows[1],rows[0],rows[2]];$("podium").innerHTML=order.map((r,i)=>r?`<div class="podium-card ${i===1?"first":""}"><div class="podium-place">${medals[i]}</div><b>${esc(r.nickname)}</b><span>${r.xp} XP</span></div>`:"<div></div>").join("");}
function records(state,rows){const season=getActiveSeason(state),weeks=new Map(),values=rows.map(r=>{const s=getPublicSeasonStats(state,r.uid,season.id);Object.entries(s.weeks||{}).forEach(([w,xp])=>weeks.set(w,(weeks.get(w)||0)+Number(xp||0)));return {...r,books:Number(s.books||0),streak:Number(s.longestStreak||0)};});const best=[...weeks.entries()].sort((a,b)=>b[1]-a[1])[0]||null,mb=Math.max(0,...values.map(r=>r.books)),ms=Math.max(0,...values.map(r=>r.streak));return {week:best?best[1]:0,books:mb,bookNames:mb?values.filter(r=>r.books===mb).map(r=>r.nickname):[],streak:ms,streakNames:ms?values.filter(r=>r.streak===ms).map(r=>r.nickname):[]};}
function ensureRecords(){if($("presentationRecords"))return;const card=document.createElement("section");card.id="presentationRecords";card.className="card";card.style.marginTop="18px";card.innerHTML='<div class="section-head"><div><h3>Klassenrekorde</h3><p>Aktuelle Season</p></div></div><div id="presentationRecordMetrics" class="metrics"></div>';$("leaderboard").closest("section")?.insertAdjacentElement("afterend",card);}
const service=await createDataService();await service.initStudentSession();$("modeBadge").textContent=service.mode==="demo"?"● DEMO":"● LIVE";$("modeBadge").className=`badge ${service.mode==="demo"?"demo":"live"}`;
service.subscribeState(state=>{const season=getActiveSeason(state),rows=rankLeaderboard(computeLeaderboard(state)),total=totalClassXp(state),goal=getSeasonGoal(state),percent=Math.min(100,Math.round(total/Math.max(1,goal)*100));$("title").textContent=state.config.className||"LESELIGA 11";$("season").textContent=season.label;$("totalXp").textContent=total;$("goalXp").textContent=goal;$("goalBar").style.width=`${percent}%`;$("goalText").textContent=total>=goal?"🎉 Season-Klassenziel erreicht – jetzt geht es um Bonus-XP!":`Noch ${goal-total} XP bis zum Season-Klassenziel.`;$("count").textContent=`${rows.length} Teilnehmer · Top 10`;$("updated").textContent=`Live · ${new Intl.DateTimeFormat("de-DE",{hour:"2-digit",minute:"2-digit"}).format(new Date())}`;renderPodium(rows);$("leaderboard").innerHTML=rows.slice(0,10).map(r=>`<div class="rank-row"><div class="rank">${r.rank}</div><div class="player"><b>${esc(r.nickname)}</b></div><div class="score">${r.xp} XP</div></div>`).join("")||'<div class="empty">Noch keine Teilnehmer.</div>';ensureRecords();const rec=records(state,rows);$("presentationRecordMetrics").innerHTML=`<div class="metric"><b>${rec.week} XP</b><span>beste Klassenwoche</span></div><div class="metric"><b>${rec.books}</b><span>meiste Bücher${rec.bookNames.length?` · ${esc(rec.bookNames.join(", "))}`:""}</span></div><div class="metric"><b>${rec.streak}</b><span>längste Streak${rec.streakNames.length?` · ${esc(rec.streakNames.join(", "))}`:""}</span></div>`;});
